### ISSUE TITLE
Incorrect 'percentofmatches' when applying FlannBasedMatcher to KAZE and SURF

### ISSUE THREAD

**Issue by yuhuazou** [BloodAxe/OpenCV-Features-Comparison#1]
When using the follwing algorithms

```
algorithms.push_back(FeatureAlgorithm("KAZE",
    new cv::KAZE(),
    new cv::FlannBasedMatcher()));
algorithms.push_back(FeatureAlgorithm("SURF FLANN",
    new cv::SurfFeatureDetector(),
    new cv::SurfDescriptorExtractor(),
    new cv::FlannBasedMatcher()));
```

The 'PercentOfMatches' value will exceed 100 as shown in this image:
![fc-matchPercent](https://f.cloud.github.com/assets/3940177/295699/702d1d2c-94aa-11e2-953d-e08b615e899a.png)

If use BFMatcher with NORM_L2 instead of FlannBasedMatcher, the values are normal.
![fc-matchPerc](https://f.cloud.github.com/assets/3940177/295700/7ea9e498-94aa-11e2-8ec0-532628d53f58.png)

**Comment by BloodAxe** [comment]
Hello. Thank you for the report.  This should be fixed in latest version.
