### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by hitimo** [BloodAxe/OpenCV-Features-Comparison#2]
Hi, 
do you have a clue where this make error comes from?
"/feature_detector_validation$ make
Scanning dependencies of target test_opencv_features2d
[ 20%] Building CXX object CMakeFiles/test_opencv_features2d.dir/main.cpp.o
/feature_detector_validation/main.cpp: In function ‘int main(int, const char**)’: /feature_detector_validation/main.cpp:71:87: error: ‘class ImageTransformation’ has no member named ‘get’"
Thanks

**Comment by BloodAxe** [comment]
This issue should be adressed to OpenCV since feature_detector_validation project is a part of OpenCV unit tests.
